In [1]:
from pycaret.classification import *
import pandas as pd

In [2]:
dataset = pd.read_csv("happydata.csv")
dataset

,infoavail,housecost,schoolquality,policetrust,streetquality,ëvents,happy
0,3,3,3,4,2,4,0
1,3,2,3,5,4,3,0
2,5,3,3,3,3,5,1
3,5,4,3,3,3,5,0
4,5,4,3,3,3,5,0
...,...,...,...,...,...,...,...
138,5,3,3,1,3,5,0
139,5,2,3,4,2,5,1
140,5,3,3,4,4,5,1
141,4,3,3,4,4,5,0
142,5,3,2,5,5,5,0

In [3]:
exp = setup(dataset, target="happy", session_id=69)

In [4]:
model = compare_models()

In [5]:
model = create_model('lightgbm')
model = tune_model(model)
evaluate_model(model)
finalize_model(model)
save_model(model, 'happiness_pipeline')

Fitting 10 folds for each of 10 candidates, totalling 100 fits

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['infoavail', 'housecost',
                                              'schoolquality', 'policetrust',
                                              'streetquality', 'ëvents'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean',
                                                               verbose='deprecated'))),
                 ('cate...
                                 boosting_type='gbdt', class_weight=None,
                                 colsample_bytree=1.0, feature_fraction=0.7,
                                 importance_type='split', learning_rate=0.05,
                                 max_depth=-1, min_child_samples=16,
                                 min_child_weight=0.001, min_split_gain=0.7,
                                 n_estimators=250, n_jobs=-1, num_leaves=10,
                                 objective=None, random_state=69, reg_alpha=1,
                                 reg_lambda=0.001, subsample=1.0,
                                 subsample_for_bin=200000, subsample_freq=0))],
          verbose=False),
 'happiness_pipeline.pkl')