# Import Library

In [85]:
import pandas as pd 
from pycaret.classification import *
import mlflow
from mlflow.models import infer_signature

# Membuat Mlflow Experiment

In [86]:
mlflow.set_tracking_uri(uri="http://127.0.0.1:5000")
mlflow.set_experiment("Mlflow Experiment")

# Menampilkan Dataset

In [87]:
dataset = pd.read_csv('heart_cleveland_upload.csv')
dataset

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,40,1,3,152,223,0,0,181,0,0.0,0,0,2,1
293,39,1,3,118,219,0,0,140,0,1.2,1,0,2,1
294,35,1,3,120,198,0,0,130,1,1.6,1,0,2,1
295,35,0,3,138,183,0,0,182,0,1.4,0,0,0,0
296,35,1,3,126,282,0,2,156,1,0.0,0,0,2,1

# Proses Train Model

In [88]:
fitur_cat = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'thal']
setup_data = setup(data = dataset, target = 'condition', categorical_features=fitur_cat)

In [89]:
best_model = compare_models(sort='Prec.', exclude=['catboost', 'xgboost','tr'])

# Mengisi Mlflow Experiment

## Exp 1

In [90]:
# Enable autologging
mlflow.autolog()

mlflow.end_run()
# Start a new MLflow run
with mlflow.start_run():
    # Create a Ridge model
    ridge_model = create_model('ridge', alpha=0.5)

2024/04/12 00:40:24 WARNING mlflow.utils.autologging_utils: You are using an unsupported version of statsmodels. If you encounter errors during autologging, try upgrading / downgrading statsmodels to a supported version, or try upgrading MLflow.
2024/04/12 00:40:24 INFO mlflow.tracking.fluent: Autologging successfully enabled for statsmodels.
2024/04/12 00:40:24 WARNING mlflow.utils.autologging_utils: You are using an unsupported version of sklearn. If you encounter errors during autologging, try upgrading / downgrading sklearn to a supported version, or try upgrading MLflow.
2024/04/12 00:40:25 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2024/04/12 00:40:25 WARNING mlflow.utils.autologging_utils: You are using an unsupported version of lightgbm. If you encounter errors during autologging, try upgrading / downgrading lightgbm to a supported version, or try upgrading MLflow.
2024/04/12 00:40:25 INFO mlflow.tracking.fluent: Autologging successfully enabled for lightgbm.

## Exp 2

In [90]:
# Enable autologging
mlflow.autolog()

mlflow.end_run()
# Start a new MLflow run
with mlflow.start_run():
    # Create a Ridge model
    ridge_model = create_model('ridge', alpha=0.5)

2024/04/12 00:40:24 WARNING mlflow.utils.autologging_utils: You are using an unsupported version of statsmodels. If you encounter errors during autologging, try upgrading / downgrading statsmodels to a supported version, or try upgrading MLflow.
2024/04/12 00:40:24 INFO mlflow.tracking.fluent: Autologging successfully enabled for statsmodels.
2024/04/12 00:40:24 WARNING mlflow.utils.autologging_utils: You are using an unsupported version of sklearn. If you encounter errors during autologging, try upgrading / downgrading sklearn to a supported version, or try upgrading MLflow.
2024/04/12 00:40:25 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2024/04/12 00:40:25 WARNING mlflow.utils.autologging_utils: You are using an unsupported version of lightgbm. If you encounter errors during autologging, try upgrading / downgrading lightgbm to a supported version, or try upgrading MLflow.
2024/04/12 00:40:25 INFO mlflow.tracking.fluent: Autologging successfully enabled for lightgbm.

## Exp 3

In [91]:
# Enable autologging
mlflow.autolog()

mlflow.end_run()
# Start a new MLflow run
with mlflow.start_run():
    # Create a Ridge model
    ridge_model = create_model('ridge', alpha=0.05)

2024/04/12 00:41:02 WARNING mlflow.utils.autologging_utils: You are using an unsupported version of statsmodels. If you encounter errors during autologging, try upgrading / downgrading statsmodels to a supported version, or try upgrading MLflow.
2024/04/12 00:41:02 INFO mlflow.tracking.fluent: Autologging successfully enabled for statsmodels.
2024/04/12 00:41:03 WARNING mlflow.utils.autologging_utils: You are using an unsupported version of sklearn. If you encounter errors during autologging, try upgrading / downgrading sklearn to a supported version, or try upgrading MLflow.
2024/04/12 00:41:03 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2024/04/12 00:41:03 WARNING mlflow.utils.autologging_utils: You are using an unsupported version of lightgbm. If you encounter errors during autologging, try upgrading / downgrading lightgbm to a supported version, or try upgrading MLflow.
2024/04/12 00:41:03 INFO mlflow.tracking.fluent: Autologging successfully enabled for lightgbm.